### ISSUE TITLE
Embedded CLI

### ISSUE THREAD

**Issue by NackJyman** [UWIT-CTS-Software/bronson_online#2]
Implement functions to call JackNet functionality from the CLI on the server side while 'main.rs' is running.

>jacknet -d proc pj -b AN AG BU

Would be able to run the search for procs and projectors in Anthropology, Agriculture, and Business. This would be convenient for testing/debugging.

**Comment by NackJyman** [comment]
Unable to type in functions that the server can see while running Windows PowerShell or cmd. Need to find a work around for Windows. Works when running on a linux system. Still needs basic implementation, no progress has been done with this idea yet.

**Comment by abryan9** [comment]
Terminal emulator web application delivers the functionality desired. Now we can just add the command to the Jquery terminal delivered to the user and prepare the server for receiving the request that gets sent.
